var CODES = {};

CODES.INFOS_DONT_EXISTS = "INFOS_DONT_EXISTS" ;
CODES.LIC_DONT_EXISTS = "LIC_DONT_EXISTS" ;
CODES.LIC_INVALID = "LIC_INVALID" ;
CODES.LIC_EXPIRED = "LIC_EXPIRED" ;

module.exports = CODES;
